# Generated by Django 3.2.15 on 2024-07-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_entite', models.CharField(max_length=100)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('cni', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('telephone', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_chambre', models.CharField(max_length=100)),
                ('id_entite', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('access', models.CharField(default='', max_length=300)),
                ('refresh', models.CharField(default='', max_length=300)),
                ('ip', models.CharField(default='', max_length=1000)),
                ('end_time', models.IntegerField(default=1724211549)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(default='super', max_length=100)),
                ('creation_date', models.IntegerField(default=1721619549)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_debut', models.IntegerField(default=0)),
                ('date_fin', models.IntegerField(default=0)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('items', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1721619549)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hpdg.client')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hpdg.entite')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('capacite', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('creation_date', models.IntegerField(default=1721619549)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hpdg.entite')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
