# Generated by Django 3.2.15 on 2023-09-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bv',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bv_name', models.CharField(max_length=100)),
                ('bv_commune', models.CharField(max_length=100)),
                ('bv_dep', models.CharField(max_length=70)),
                ('bv_region', models.CharField(max_length=100)),
                ('bv_pays', models.CharField(max_length=200)),
                ('bv_recolte', models.IntegerField(default=0)),
                ('bv_attente', models.IntegerField(default=0)),
                ('bv_vol1', models.CharField(default='none', max_length=200)),
                ('bv_vol2', models.CharField(default='none', max_length=200)),
                ('bv_vol3', models.CharField(default='none', max_length=200)),
                ('bv_vol4', models.CharField(default='none', max_length=200)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('com_name', models.CharField(max_length=100)),
                ('com_dec', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_dep', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('initiateur', models.CharField(max_length=100)),
                ('interlocuteur', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('last_message', models.CharField(max_length=10000)),
                ('last_date', models.IntegerField()),
                ('last_writer', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=1)),
                ('time', models.IntegerField()),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('sexe', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=200)),
                ('cni', models.CharField(max_length=200)),
                ('numero_ce', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('parrain', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('departement_org', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('sympathisant', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('is_read', models.BooleanField(auto_created=True, default=False)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('disc_id', models.CharField(max_length=100)),
                ('emetteur', models.CharField(max_length=100)),
                ('recepteur', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=10000)),
                ('date_envoi', models.IntegerField()),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('pays_dep', models.CharField(default='', max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('alpha3', models.CharField(max_length=100)),
                ('alpha2', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100)),
                ('nom_eng', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('sexe', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=200)),
                ('cni', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('parrain', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('departement_org', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('sympathisant', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('reg_name', models.CharField(max_length=100)),
                ('reg_der', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('creation_date', models.IntegerField(auto_created=True, default=1695751406)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('photo', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('cni', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('parti', models.CharField(max_length=200)),
                ('matricule', models.CharField(max_length=200)),
                ('parrain', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('departement_org', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('sympathisant', models.CharField(max_length=100)),
                ('preinscrit', models.BooleanField(default=False)),
                ('inscrit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.DeleteModel(
            name='Atelier',
        ),
    ]
