# Generated by Django 3.2.15 on 2024-07-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='entite',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='photo',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.IntegerField(default=1724211708),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1721619708),
        ),
    ]
