# Generated by Django 3.2.15 on 2023-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0002_auto_20230926_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bv',
            name='bv_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bv',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='commune',
            name='com_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='departement',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='departement',
            name='dep_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='info',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='numero_ce',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='cni',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='region',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(auto_created=True, default=1696057165),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
