# Generated by Django 3.2.15 on 2024-07-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0004_auto_20240723_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='entite',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='photo',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.IntegerField(default=1724364398),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1721772398),
        ),
    ]
