# Generated by Django 3.2.15 on 2023-10-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0009_auto_20231008_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='bv',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bv',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='discussion',
            name='last_message_statut',
            field=models.CharField(default='sent', max_length=100),
        ),
        migrations.AddField(
            model_name='inscription',
            name='edition',
            field=models.CharField(default='2023', max_length=200),
        ),
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='etat',
            field=models.CharField(default='sent', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='mediatype',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='pays',
            name='continent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='edition',
            field=models.CharField(default='2023', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='pays',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='comite_base',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='onlinetime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sous_commite_arr',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='bv',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='commune',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='departement',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='info',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='info',
            name='time',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='pays',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='region',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(default=1698363327),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='citoyen', max_length=200),
        ),
    ]
