# Generated by Django 3.2.15 on 2023-12-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0010_auto_20231012_1827'),
        ('hpdg', '0014_auto_20231128_0842'),
    ]

    operations = [
    ]
