# Generated by Django 3.2.15 on 2024-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0023_auto_20240208_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('info', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('contenu', models.CharField(max_length=10000)),
                ('statut', models.CharField(default='1', max_length=1)),
                ('time', models.IntegerField(default=1707478345)),
                ('creation_date', models.IntegerField(default=1707478345)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('info', models.CharField(max_length=1000)),
                ('commentaire', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=1000)),
                ('type', models.CharField(default='like', max_length=10)),
                ('statut', models.CharField(default='1', max_length=1)),
                ('time', models.IntegerField(default=1707478345)),
                ('creation_date', models.IntegerField(default=1707478345)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddField(
            model_name='info',
            name='contenu',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='bv',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='bv',
            name='last_modified',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='commune',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='departement',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='info',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='info',
            name='time',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_modif',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='pays',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='region',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
        migrations.AlterField(
            model_name='token',
            name='end_time',
            field=models.IntegerField(default=1710070345),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(default=1707478345),
        ),
    ]
