# Generated by Django 3.2.15 on 2024-02-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0025_auto_20240210_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('access', models.CharField(default='', max_length=300)),
                ('refresh', models.CharField(default='', max_length=300)),
                ('ip', models.CharField(default='', max_length=1000)),
                ('end_time', models.IntegerField(default=1710463176)),
                ('creation_date', models.IntegerField(default=1707871176)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='path',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='title',
        ),
        migrations.RemoveField(
            model_name='token',
            name='access',
        ),
        migrations.RemoveField(
            model_name='token',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='token',
            name='ips',
        ),
        migrations.RemoveField(
            model_name='token',
            name='refresh',
        ),
        migrations.AlterField(
            model_name='bv',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='bv',
            name='last_modified',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='commune',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='departement',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='info',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='info',
            name='time',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_modif',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='pays',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='commentaire',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='time',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='region',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.IntegerField(default=1707871176),
        ),
    ]
