# Generated by Django 3.2.15 on 2024-06-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdg', '0029_auto_20240216_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_entite', models.CharField(max_length=100)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('capacite', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('photo', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('cni', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('telephone', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_chambre', models.CharField(max_length=100)),
                ('id_entite', models.CharField(max_length=100)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_client', models.CharField(max_length=100)),
                ('date_debut', models.IntegerField(default=0)),
                ('date_fin', models.IntegerField(default=0)),
                ('statut', models.CharField(default='1', max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('items', models.CharField(max_length=200)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.IntegerField(default=1717807303)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.DeleteModel(
            name='Bv',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
        migrations.DeleteModel(
            name='Preinscription',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='session',
            name='creation_date',
            field=models.IntegerField(default=1717807303),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.IntegerField(default=1720399303),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.IntegerField(default=1717807303),
        ),
    ]
